#!/usr/bin/env python3
"""Summarize bench_results.jsonl into BENCHMARK_RESULTS.md.

Statistics (fixed before looking at the data):
- Success / recall / error rates per profile: Wilson 95% interval.
- Latency per profile: median with a 95% bootstrap percentile interval
  (2000 resamples, seeded). Latency includes CLI startup; profiles share
  it, so differences are attributable to the routing path only in
  expectation, never per-run.
- Pairwise profile comparison (relay minus native) on success: difference
  of proportions with a Newcombe-style interval derived from the Wilson
  bounds; if the interval contains 0 the result is INCONCLUSIVE.
- Provider calls/tokens are only known for relay profiles (sanitized relay
  log); native usage is reported as unknown, not as zero.
A finite sample cannot establish zero degradation; the report says so.
"""
from __future__ import annotations

import json
import math
import pathlib
import random
import statistics
import sys

HERE = pathlib.Path(__file__).resolve().parent
Z = 1.959964


def wilson(k: int, n: int):
    if n == 0:
        return (float("nan"), float("nan"), float("nan"))
    p = k / n
    denom = 1 + Z * Z / n
    centre = (p + Z * Z / (2 * n)) / denom
    half = Z * math.sqrt(p * (1 - p) / n + Z * Z / (4 * n * n)) / denom
    return (p, max(0.0, centre - half), min(1.0, centre + half))


def boot_median(xs, seed=1):
    if not xs:
        return (float("nan"), float("nan"), float("nan"))
    rng = random.Random(seed)
    meds = []
    for _ in range(2000):
        sample = [rng.choice(xs) for _ in xs]
        meds.append(statistics.median(sample))
    meds.sort()
    return (statistics.median(xs), meds[int(0.025 * len(meds))],
            meds[int(0.975 * len(meds)) - 1])


def newcombe(k1, n1, k2, n2):
    """Difference p1-p2 with the Newcombe hybrid score interval."""
    p1, l1, u1 = wilson(k1, n1)
    p2, l2, u2 = wilson(k2, n2)
    d = p1 - p2
    lo = d - math.sqrt((p1 - l1) ** 2 + (u2 - p2) ** 2)
    hi = d + math.sqrt((u1 - p1) ** 2 + (p2 - l2) ** 2)
    return d, lo, hi


def pct(t):
    return "%.0f%% [%.0f%%, %.0f%%]" % (t[0] * 100, t[1] * 100, t[2] * 100)


def main() -> int:
    rows = [json.loads(l) for l in open(HERE / "bench_results.jsonl")]
    plan = json.loads((HERE / "bench_plan.json").read_text())
    profiles = ["native", "legacy", "durable"]
    by = {p: [r for r in rows if r["profile"] == p] for p in profiles}
    lines = ["# Benchmark results — matched evaluation (Step 7)", "",
             "Generated by `qualification/bench/summarize.py` from "
             "`bench_results.jsonl`; plan in `bench_plan.json` (seed %d, "
             "%d repeats, model `%s`, started %s UTC, %d runs)." % (
                 plan["seed"], plan["repeats"], plan["model"],
                 plan["started"], len(rows)), "",
             "Comparison is **approximate**: same CLI, model selector, "
             "prompts, fixtures, machine and permission modes; only the "
             "endpoint differs. Native usage/billing is not observable "
             "from the relay logs and is reported as unknown. Latency "
             "includes CLI startup and the provider's own variance.", ""]
    lines += ["## Per profile", "",
              "| Profile | Runs | Task success | Restart recall | "
              "CLI errors | Task latency median s [95% CI] | "
              "Recall latency median s | Provider calls (sum) | "
              "Tokens in/out (sum) |", "|---|---|---|---|---|---|---|---|---|"]
    for p in profiles:
        rs = by[p]
        n = len(rs)
        succ = sum(1 for r in rs if r["success"])
        recall_rows = [r for r in rs if r.get("recall")]
        rec = sum(1 for r in recall_rows if r["recall"]["success"])
        errs = sum(1 for r in rs if r["step1"]["exit"] != 0)
        lat = [r["step1"]["seconds"] for r in rs]
        rlat = [r["recall"]["seconds"] for r in recall_rows]
        m = boot_median(lat)
        rm = boot_median(rlat)
        calls = [r["usage"]["provider_calls"] for r in rs
                 if r["usage"]["provider_calls"] is not None]
        toks_in = [r["usage"]["input_tokens"] for r in rs
                   if r["usage"]["input_tokens"] is not None]
        toks_out = [r["usage"]["output_tokens"] for r in rs
                    if r["usage"]["output_tokens"] is not None]
        lines.append("| %s | %d | %s | %s | %s | %.1f [%.1f, %.1f] | %.1f | %s | %s |" % (
            p, n, pct(wilson(succ, n)),
            pct(wilson(rec, len(recall_rows))) if recall_rows else "n/a",
            pct(wilson(errs, n)), m[0], m[1], m[2], rm[0],
            sum(calls) if calls else "unknown",
            ("%d/%d" % (sum(toks_in), sum(toks_out))) if toks_in
            else "unknown"))
    lines += ["", "## Per task (success count / runs)", "",
              "| Task | Category | " + " | ".join(profiles) + " |",
              "|---|---|" + "---|" * len(profiles)]
    tasks = []
    for r in rows:
        if r["task"] not in [t[0] for t in tasks]:
            tasks.append((r["task"], r["category"]))
    for tid, cat in tasks:
        cells = []
        for p in profiles:
            rs = [r for r in by[p] if r["task"] == tid]
            cells.append("%d/%d (recall %d/%d)" % (
                sum(1 for r in rs if r["success"]), len(rs),
                sum(1 for r in rs if r.get("recall")
                    and r["recall"]["success"]),
                sum(1 for r in rs if r.get("recall"))))
        lines.append("| %s | %s | %s |" % (tid, cat, " | ".join(cells)))
    lines += ["", "## Relay vs native (difference of success proportions)",
              ""]
    n_nat = len(by["native"])
    k_nat = sum(1 for r in by["native"] if r["success"])
    for p in ("legacy", "durable"):
        n_p = len(by[p])
        k_p = sum(1 for r in by[p] if r["success"])
        d, lo, hi = newcombe(k_p, n_p, k_nat, n_nat)
        verdict = "INCONCLUSIVE (interval contains 0)" if lo <= 0 <= hi \
            else ("relay better" if lo > 0 else "relay worse")
        lines.append("- %s − native: %+.0f pp [%+.0f, %+.0f] → %s" % (
            p, d * 100, lo * 100, hi * 100, verdict))
    lines += ["", "## Errors observed", "",
              "Reading guide: for the `durable` profile every RESUME step "
              "first fails closed (`request_error`, "
              "`legacy continuation unavailable`) because `devin -r` "
              "rewrites the wire session seed; the experimental host then "
              "records an explicit `legacy_history` epoch transition and "
              "retries once — the recall succeeded in those runs, so these "
              "rows are the designed fail-closed-then-adopt path, not "
              "failures. `selection_unconfirmed` rows were a real relay "
              "defect (AssignModel/GetChatMessage overlap) fixed after this "
              "run with a bounded grace wait; the affected task failed on "
              "the native profile too because the SWE-2 sidekick was "
              "rate-limited by Cognition during the run "
              "(`ANSWER unavailable (sidekick rate-limited)`).", ""]
    any_err = False
    for r in rows:
        if r["step1"]["exit"] != 0 or (r.get("recall")
                                       and r["recall"]["exit"] != 0):
            any_err = True
            lines.append("- run %d %s/%s r%d: exit %s (%s); recall exit %s (%s)" % (
                r["n"], r["profile"], r["task"], r["repeat"],
                r["step1"]["exit"], r["step1"]["error_class"],
                r["recall"]["exit"] if r.get("recall") else "n/a",
                r["recall"]["error_class"] if r.get("recall") else "n/a"))
        if r["usage"].get("errors"):
            any_err = True
            lines.append("- run %d %s/%s: relay-side error categories %s" % (
                r["n"], r["profile"], r["task"], r["usage"]["errors"]))
    if not any_err:
        lines.append("- none")
    lines += ["", "## Limitations", "",
              "- %d runs per profile is a small sample; intervals are wide "
              "by design and a finite sample cannot establish zero "
              "degradation." % (len(rows) // len(profiles)),
              "- Latency is end-to-end CLI wall time (startup + inference "
              "+ tools); provider-side variance dominates.",
              "- Native token usage and billing are not observable here.",
              "- Cold/warm cache is not controlled: every run is a fresh "
              "session (cold prompt cache) for all profiles alike.",
              "- Tasks are short; long-running, interruption-heavy work "
              "is covered by the live matrix, not by this benchmark."]
    (HERE / "BENCHMARK_RESULTS.md").write_text("\n".join(lines) + "\n")
    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    sys.exit(main())
